# TCL File Generated by Component Editor 13.1
# Wed Feb 13 17:00:54 GMT-03:00 2019
# DO NOT MODIFY


# 
# Arbitro4 "Arbitro4" v1.0
#  2019.02.13.17:00:54
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module Arbitro4
# 
set_module_property DESCRIPTION ""
set_module_property NAME Arbitro4
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Arbitro4
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Lamaquina
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file Lamaquina.sv SYSTEM_VERILOG PATH Lamaquina.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter Idle STD_LOGIC_VECTOR 0
set_parameter_property Idle DEFAULT_VALUE 0
set_parameter_property Idle DISPLAY_NAME Idle
set_parameter_property Idle TYPE STD_LOGIC_VECTOR
set_parameter_property Idle UNITS None
set_parameter_property Idle ALLOWED_RANGES 0:15
set_parameter_property Idle HDL_PARAMETER true
add_parameter Checksum STD_LOGIC_VECTOR 1
set_parameter_property Checksum DEFAULT_VALUE 1
set_parameter_property Checksum DISPLAY_NAME Checksum
set_parameter_property Checksum TYPE STD_LOGIC_VECTOR
set_parameter_property Checksum UNITS None
set_parameter_property Checksum ALLOWED_RANGES 0:15
set_parameter_property Checksum HDL_PARAMETER true
add_parameter TimeOut1 STD_LOGIC_VECTOR 2
set_parameter_property TimeOut1 DEFAULT_VALUE 2
set_parameter_property TimeOut1 DISPLAY_NAME TimeOut1
set_parameter_property TimeOut1 TYPE STD_LOGIC_VECTOR
set_parameter_property TimeOut1 UNITS None
set_parameter_property TimeOut1 ALLOWED_RANGES 0:15
set_parameter_property TimeOut1 HDL_PARAMETER true
add_parameter SendBack STD_LOGIC_VECTOR 3
set_parameter_property SendBack DEFAULT_VALUE 3
set_parameter_property SendBack DISPLAY_NAME SendBack
set_parameter_property SendBack TYPE STD_LOGIC_VECTOR
set_parameter_property SendBack UNITS None
set_parameter_property SendBack ALLOWED_RANGES 0:15
set_parameter_property SendBack HDL_PARAMETER true
add_parameter TryAlarm STD_LOGIC_VECTOR 4
set_parameter_property TryAlarm DEFAULT_VALUE 4
set_parameter_property TryAlarm DISPLAY_NAME TryAlarm
set_parameter_property TryAlarm TYPE STD_LOGIC_VECTOR
set_parameter_property TryAlarm UNITS None
set_parameter_property TryAlarm ALLOWED_RANGES 0:15
set_parameter_property TryAlarm HDL_PARAMETER true
add_parameter Alarm STD_LOGIC_VECTOR 5
set_parameter_property Alarm DEFAULT_VALUE 5
set_parameter_property Alarm DISPLAY_NAME Alarm
set_parameter_property Alarm TYPE STD_LOGIC_VECTOR
set_parameter_property Alarm UNITS None
set_parameter_property Alarm ALLOWED_RANGES 0:15
set_parameter_property Alarm HDL_PARAMETER true
add_parameter Timer STD_LOGIC_VECTOR 6
set_parameter_property Timer DEFAULT_VALUE 6
set_parameter_property Timer DISPLAY_NAME Timer
set_parameter_property Timer TYPE STD_LOGIC_VECTOR
set_parameter_property Timer UNITS None
set_parameter_property Timer ALLOWED_RANGES 0:15
set_parameter_property Timer HDL_PARAMETER true
add_parameter temp INTEGER 10000
set_parameter_property temp DEFAULT_VALUE 10000
set_parameter_property temp DISPLAY_NAME temp
set_parameter_property temp TYPE INTEGER
set_parameter_property temp UNITS None
set_parameter_property temp ALLOWED_RANGES -2147483648:2147483647
set_parameter_property temp HDL_PARAMETER true
add_parameter temp2 INTEGER 3
set_parameter_property temp2 DEFAULT_VALUE 3
set_parameter_property temp2 DISPLAY_NAME temp2
set_parameter_property temp2 TYPE INTEGER
set_parameter_property temp2 UNITS None
set_parameter_property temp2 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property temp2 HDL_PARAMETER true


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 2
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave CMSIS_SVD_VARIABLES ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave clk clk Input 1
add_interface_port nios_custom_instruction_slave dataa dataa Input 32
add_interface_port nios_custom_instruction_slave reset reset Input 1
add_interface_port nios_custom_instruction_slave enable clk_en Input 1
add_interface_port nios_custom_instruction_slave result result Output 32
add_interface_port nios_custom_instruction_slave done done Output 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock ""
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end rx export Input 1
add_interface_port conduit_end tx export Output 1

